name: Haber Botu CI/CD

# Ne zaman Ã§alÄ±ÅŸsÄ±n? -> Main dalÄ±na kod atÄ±ldÄ±ÄŸÄ±nda
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manuel tetikleme butonu

jobs:
  # GÃ–REV 1: ALTYAPIYI GÃœNCELLE (Terraform)
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: /home/ibrahim/news-terraform # Terraform dosyalarÄ±n nerede?

    steps:
    - name: Kodu Ã‡ek (Checkout)
      uses: actions/checkout@v3

    - name: AWS KimliÄŸini TanÄ±t
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Kurulumu
      uses: hashicorp/setup-terraform@v2

    - name: Terraform BaÅŸlat (Init)
      run: terraform init

    - name: AltyapÄ±yÄ± Kur (Apply)
      # -auto-approve: Bana soru sorma, direkt yap demek.
      run: terraform apply -auto-approve

---

### ğŸš€ AdÄ±m 4: FÄ±rlatma! (Push)

Her ÅŸey hazÄ±r. Åimdi kodlarÄ±nÄ± GitHub'a gÃ¶nderelim ve ÅŸovu izleyelim.

Terminali proje ana klasÃ¶rÃ¼nde aÃ§

```bash
git init 
git add .
git commit -m "CI/CD boru hattÄ± eklendi ve Remote State'e geÃ§ildi"
git branch -M main
git remote add origin https://github.com/sutluibrahim3-netizen/Terraform-AI-Pipeline
git push -u origin main

    
